### ISSUE TITLE
Final round of testing before migrating my own blog

### ISSUE THREAD

**Issue by jipiboily** [jipiboily/vocal#42]
Includes but not limited to:
- [ ] test with multiple browsers
- [x] test with tablets (both) and phones (Nexus 4 + iPhone)
- [ ] test RSS with ReadKit and maybe another client or two
- [ ] test sharing buttons (especially for URL)
- [ ] test Twitter Card + FB Open Graph
- [ ] ...

**Comment by msevestre** [comment]
oh oh....

**Comment by jipiboily** [comment]
Yeah, not there yet, but "soon™". You can see the progress on https://waffle.io/jipiboily/vocal :)

**Comment by jipiboily** [comment]
Getting there...basically, next steps are:
- create a new Rails app and try Vocal
- document setup
- test it on real mobile devices
- all other tests previously stated.

All known bugs preventing a 0.0.1 are now closed.

**Comment by jipiboily** [comment]
Stuff specified in last comment was all done. Need some mobile love plus some testing for RSS and social sharing, that's pretty much it to be able to use Vocal for my own blog!

**Comment by jipiboily** [comment]
That's pretty much ready for a 0.0.1 release. Closing this for now. Watch out my blog in the next week or so. :)
